### ISSUE TITLE
Problem with quotes

### ISSUE THREAD

**Issue by danielkh** [undadasea/headhunter-monitor#3]
`Python-Docker    | Traceback (most recent call last):
Python-Docker    |   File "./Monitor.py", line 54, in <module>
Python-Docker    |     insertVacancy(cursor, vacancy)
Python-Docker    |   File "/parse.py", line 75, in insertVacancy
Python-Docker    |     cursor.execute("INSERT INTO vacancies(id, \
Python-Docker    | psycopg2.errors.SyntaxError: syntax error at or near "Core"
Python-Docker    | LINE 1: ...4492662,'С++ Developer (Cross Platform Profilers' Core)',Fal...`

It happens when there is a single-quote in the name field for the provided dict/json. The example of such structure is provided below:

> in insert:  {'id': '34492662', 'premium': False, 'name': "С++ Developer (Cross Platform Profilers' Core)"

**Comment by undadasea** [comment]
Commit 6d188ad: would that be a solution?

(uncommented part with pages is commented back now)

**Comment by danielkh** [comment]
Now it works! Thanks! Probably somewhen in the future such situations might be solved in general by the psycopg2 parameters as it is described here: http://initd.org/psycopg/docs/usage.html#query-parameters
